### ISSUE TITLE
Not showing the picker

### ISSUE THREAD

**Issue by vivekparekh8** [bamlab/react-native-numberpicker-dialog#1]
### Warning showed : Unhandled promise rejection

Call to picker : 
`//import and stuff`
`<TouchableHighlight`
          `style={{`
            `height: 40,`
            `margin: 10,`
            `alignSelf: 'center',`
            `borderWidth: 1`
        `}}`
        `onPress={() => {`
        `NumberPickerDialog.show({`
        `values: ['First item', 'Second item', 'Third item'],`
        `positiveButtonLabel: 'Ok',`
        `negativeButtonLabel: 'Cancel',`
        `message: 'What would you like to have?',`
        `title: 'Nice dialog',`
        `}).then((id) => {`
        `// id is the index of the chosen item, or -1 if the user cancelled.`
        `}).catch((err) => {});`
        `}}`
      `>`
        `<Text>Show Picker</Text>`
`</TouchableHighlight>`

**Comment by vivekparekh8** [comment]
Error related to native package.
Resolved by adding `new RNNumberPickerDialogPackage()` at line 27 in MainApplication.java

**Comment by ruchirgarg** [comment]
This is still happening for me.
new RNNumberPickerDialogPackage() is already added in my MainApplication.java
Can anyone help?
